Feature/health check unit tests
ChanduCES/EmployeeApp pull request #1
Opened 2023-08-08 13:52 UTC by ChanduCES

2023-08-08 14:53 UTC, vaishali3012 requested changes

2023-08-08 14:53 UTC, vaishali3012 commented on src/EmployeeApp/EmployeeApp.API/Constants/Endpoints.cs
> +    public static class Endpoints
Suggestion : You can keep classame as ApiRoutes to keep consistency

2023-08-08 14:58 UTC, ChanduCES commented on src/EmployeeApp/EmployeeApp.API/Constants/Endpoints.cs
> +    public static class Endpoints
Changes done

2023-08-09 10:46 UTC, kumardeepak99 commented on src/EmployeeApp/EmployeeApp.IntegrationTest/SwaggerIntegrationTests.cs
> +            title.Should().BeEquivalentTo(AppConstants.EmployeeAppAPI);
suggestion: use Should().Be() to compare two values.

2023-08-09 15:41 UTC, merged

2023-08-09 15:59 UTC, rohitvipin commented on src/EmployeeApp/EmployeeApp.API/Constants/ApiRoutes.cs
> +        public const string SwaggerEndpoint = "/swagger/v1/swagger.json";
this is not used anywhere in the api, if its only used in test please move there

2023-08-09 15:59 UTC, rohitvipin commented on src/EmployeeApp/EmployeeApp.API/Constants/AppConstants.cs
> +    public static class AppConstants
these are not used in the app

2023-08-09 15:59 UTC, rohitvipin commented on src/EmployeeApp/EmployeeApp.API/EmployeeApp.API.csproj
> +  <ItemGroup>
Why?

2023-08-09 15:59 UTC, rohitvipin commented on src/EmployeeApp/EmployeeApp.API/EmployeeApp.API.csproj
> +    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="7.0.9" />
Why?

2023-08-09 15:59 UTC, rohitvipin commented on src/EmployeeApp/EmployeeApp.API/Program.cs
> +        builder.Services.AddMvcCore();
Why?

2023-08-09 15:59 UTC, rohitvipin commented on src/EmployeeApp/EmployeeApp.IntegrationTest/SwaggerIntegrationTests.cs
> +            var json = JsonConvert.DeserializeObject<JToken>(result);
what you deserialize is a json? then rather just use JObject

2023-08-10 07:03 UTC, ChanduCES commented on src/EmployeeApp/EmployeeApp.IntegrationTest/SwaggerIntegrationTests.cs
> +            var json = JsonConvert.DeserializeObject<JToken>(result);
Using JObject

2023-08-10 07:04 UTC, ChanduCES commented on src/EmployeeApp/EmployeeApp.API/EmployeeApp.API.csproj
> +  <ItemGroup>
This is for the swagger integration

2023-08-10 07:04 UTC, ChanduCES commented on src/EmployeeApp/EmployeeApp.API/EmployeeApp.API.csproj
> +    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="7.0.9" />
This is for the swagger integration

2023-08-10 07:18 UTC, rohitvipin commented on src/EmployeeApp/EmployeeApp.API/EmployeeApp.API.csproj
> +    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="7.0.9" />
Not required. Please remove and see. 
please don’t add things unless it’s really required. 
https://learn.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-7.0&tabs=visual-studio